name: Create latest fleetctl package

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:        # Allow manual triggers

jobs:
  check-fleet-release:
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.check_release.outputs.new_release }}
      version: ${{ steps.check_release.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check latest Fleet release
        id: check_release
        run: |
          LATEST=$(curl -s https://api.github.com/repos/fleetdm/fleet/releases/latest | jq -r .tag_name)
          
          # Create version file if it doesn't exist
          if [ ! -f "current_fleetctl_version.txt" ]; then
            echo "none" > current_fleetctl_version.txt
          fi
          
          CURRENT=$(cat current_fleetctl_version.txt)
          
          if [ "$LATEST" != "$CURRENT" ]; then
            echo "new_release=true" >> $GITHUB_OUTPUT
            echo "version=${LATEST#v}" >> $GITHUB_OUTPUT
          else
            echo "new_release=false" >> $GITHUB_OUTPUT
          fi

  create-package:
    needs: check-fleet-release
    if: needs.check-fleet-release.outputs.new_release == 'true'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Fleet package
        run: |
          chmod +x ./.github/scripts/create_fleetctl_package.sh
          ./.github/scripts/create_fleetctl_package.sh
        env:
          FLEET_VERSION: ${{ needs.check-fleet-release.outputs.version }}
          PACKAGE_AUTOMATION_TOKEN: ${{ secrets.PACKAGE_AUTOMATION_TOKEN }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}

      - name: Update version file
        if: success()
        run: |
          echo "v${{ needs.check-fleet-release.outputs.version }}" > current_fleetctl_version.txt
          git config user.name "${{ secrets.USER_NAME }}"
          git config user.email "${{ secrets.USER_EMAIL }}"
          git add current_fleetctl_version.txt
          git commit -m "Update Fleet version to v${{ needs.check-fleet-release.outputs.version }}"
          git push